application: ocn-gg
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /assets
  static_dir: assets
- url: /crons/.*
  script: main.app
  login: admin
- url: /.*
  script: main.app
  
libraries:
- name: jinja2
  version: latest
- name: numpy
  version: "latest"
